export default [
  { path: "/login", component: "../features/auth/LoginPage", layout: false },
  { path: "/", redirect: "/welcome" },
  { path: "/welcome", name: "欢迎", icon: "HomeOutlined", component: "../features/welcome/WelcomePage" },
  { path: "/blog/posts", name: "文章", icon: "FileTextOutlined", component: "../features/blog/PostsPage", access: "canPosts" },
  { path: "/blog/posts/new", component: "../features/blog/PostEditorPage", access: "canPosts", hideInMenu: true },
  { path: "/blog/posts/:postId/edit", component: "../features/blog/PostEditorPage", access: "canPosts", hideInMenu: true },
  { path: "/blog/categories", name: "分类", icon: "FolderOutlined", component: "../features/blog/CategoriesPage", access: "canCategories" },
  { path: "/blog/tags", name: "标签", icon: "TagsOutlined", component: "../features/blog/TagsPage", access: "canTags" },
  { path: "/users", name: "用户", icon: "UserOutlined", component: "../features/users/UsersPage", access: "canUsers" },
  { path: "/admins", name: "管理员", icon: "TeamOutlined", component: "../features/admins/AdminsPage", access: "canAdmins" },
  { path: "/roles", name: "角色权限", icon: "SafetyCertificateOutlined", component: "../features/roles/RolesPage", access: "canRoles" },
  { path: "/assets", name: "文件资产", icon: "FolderOpenOutlined", component: "../features/assets/AssetsPage", access: "canAssets" },
  { path: "/settings", name: "系统设置", icon: "SettingOutlined", component: "../features/settings/SettingsPage", access: "canSettings" },
  { path: "/security", name: "安全日志", icon: "AuditOutlined", component: "../features/security/SecurityPage", access: "canSecurity" },
  { path: "/system", name: "系统状态", icon: "DashboardOutlined", component: "../features/system/SystemStatusPage", access: "canSystem" },
  { path: "/account/settings", name: "个人设置", component: "../features/account/AccountSettingsPage", hideInMenu: true },
  { path: "*", redirect: "/welcome" },
];
